app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name="home"),
    path('signup/', views.CreateProfile.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logout_request, name="logout"),
    path('edit/<int:pk>', views.EditView.as_view(), name="edit")
    #path('edit/<slug:slug>', views.EditView.as_view())
]

django_user_profile/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('app.urls', namespace='app')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from .task import send_new_user_email
from PIL import Image

class UserProfile(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    location = models.CharField(max_length=100, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    image = models.ImageField(default='user.svg', upload_to='profile_pics')

    class Meta:
        ordering = ['user']
        db_table = 'user_profiles'

    def __str__(self):
        return self.user.username


@receiver(signal=pre_save, sender=User)
def create_username(sender, instance, *args, **kwargs):
    instance.username = instance.first_name[:1] + instance.last_name


@receiver(signal=post_save, sender=User)
def create_or_update_profile(sender, instance, created, **kwargs):
    if created:
        location = getattr(instance, 'location', None)
        birthday = getattr(instance, 'birthday', None)
        image = getattr(instance, 'image', None)
        profile = UserProfile.objects.create(user=instance, location=location, birthdate=birthday, image=image)
        send_new_user_email.delay(instance.email)
    instance.userprofile.save()

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile
from django.contrib.auth.models import User
from django.forms.models import inlineformset_factory
from django.forms import ModelForm

class CustomUserCreateForm(UserCreationForm):
    location = forms.CharField()
    birthday = forms.DateField()
    image = forms.FileField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        password = self.cleaned_data.get('password1')
        user.set_password(password)
        user.location = self.cleaned_data.get('location')
        user.birthday = self.cleaned_data.get('birthday')
        user.image = self.cleaned_data.get('image')
        user.save()
        return user


class EditUserProfileForm(ModelForm):
    first_name = forms.CharField(max_length=256, required=False)
    last_name = forms.CharField(max_length=256, required=False)
    #username = forms.CharField(max_length=256)

    def __init__(self, *args, **kwargs):
        super(EditUserProfileForm, self).__init__(*args, **kwargs)
        try:
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['last_name'].initial = self.instance.user.last_name
            #self.fields['username'].initial = self.instance.user.username
        except User.DoesNotExist:
            pass

    class Meta:
        model = UserProfile
        fields = '__all__'
        exclude = ['user',]

    def save(self, commit=True):
        profile = super(EditUserProfileForm, self).save(commit=False)
        user = profile.user
        user.first_name = self.cleaned_data.get('first_name', None)
        user.last_name = self.cleaned_data.get('last_name', None)
        user.save()
        profile.save()
        return profile

UserProfileFormset = inlineformset_factory(User, UserProfile, fields=('location',))

app/views.py
from django.shortcuts import render
from django.views import generic
from .task import add
from .forms import CustomUserCreateForm, EditUserProfileForm
from .models import UserProfile
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic.detail import SingleObjectMixin
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.
class IndexView(generic.TemplateView):
    template_name = "home.html"


class CreateProfile(generic.CreateView):
    template_name = "signup.html"
    form_class = CustomUserCreateForm
    success_url = '/login'

    def post(self, request, *args, **kwargs):
        form = CustomUserCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Account was created for " + form.cleaned_data["first_name"]
                             + " " + form.cleaned_data["last_name"])
            return redirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form})


    '''def form_valid(self, form):
        form.save()
        return super(CreateProfile, self).form_valid(form)'''


class LoginView(generic.FormView):
    template_name = "login.html"
    form_class = AuthenticationForm
    success_url = "/"

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is None:
            messages.error(request=self.request, message="Invalid credentials")
        else:
            login(self.request, user)
            messages.success(self.request, "You are logged in")
            return redirect(self.success_url)


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect('/')


class EditView(generic.UpdateView):
    model = UserProfile
    template_name = "signup.html"
    form_class = EditUserProfileForm
    success_url = "/"

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{% block title %} Welcome!!!{% endblock %}</title>
</head>

<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Welcome!!!</h1>
        {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'app:logout' %}">Logout</a>
            <a href="{% url 'app:edit' user.userprofile.pk %}">Edit Profile</a>
        {% else %}
            <a href="{% url 'app:login' %}">Login</a>
        {% endif %}

    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        {% for message in messages %}
            {{ message }}
        {% endfor%}
    </div>
    <div class="container" style="max-width:600px">
        <div class="py-5">
            <div class="row">
                <div class="col-12">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit">
                    </form>
                </div>
            </div>
        </div>
        <a href="{% url 'app:signup' %}">Create profile</a>
    </div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% block content %}
    <div class="container" style="max-width:600px">
        <div class="py-5">
            <div class="row">
                <div class="col-12">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}